API_ID = 123456        # Telegram api_id
API_HASH = "API_HASH"
BOT_TOKEN = "BOT_TOKEN"

OWNER_ID = 123456789   # Your Telegram ID

# AUTOREPLY SETTINGS
AUTOREPLY_DELAY_MIN = 60
AUTOREPLY_DELAY_MAX = 90
AUTOREPLY_DAILY_LIMIT = 15

# STORY MENTION
MAX_MENTIONS_PER_RUN = 15
MENTION_DELAY_MIN = 20
MENTION_DELAY_MAX = 40
